### ISSUE TITLE
Broken for Distributions?

### ISSUE THREAD

**Issue by Nosferican** [JuliaPlots/StatsPlots.jl#195]
```
Distributions v0.16.4
Plots v0.20.6
StatPlots v0.8.1
```
```
using Distributions, Plots, StatPlots
plot(Normal())
No user recipe for Normal{Float64}
```

**Comment by mkborregaard** [comment]
I can't reproduce. Try again without loading `Plots`, i.e. just `using Distributions, StatPlots` in a fresh session?

**Comment by Nosferican** [comment]
Without loading `Plots` it works fine. When loading `Plots` before calling it I get the `No user recipe for ...` error.

**Comment by mkborregaard** [comment]
Yes, there is some weird interaction going on with the reexport of Plots - always have been. You should never load Plots before StatPlots though, so that is the solution to the issue today.

The solution in the longer run will most likely be to not reexport Plots, and thus require you to load Plots.

**Comment by mkborregaard** [comment]
> The solution in the longer run will most likely be to not reexport Plots, and thus require you to load Plots.

That doesn't look like the right solution after trying it out in practice. But the issue here seems to have resolved itself.
