### ISSUE TITLE
groupedbar overrides group ordering alphabetically?

### ISSUE THREAD

**Issue by Shushman** [JuliaPlots/StatsPlots.jl#291]
If my groups are `groupvals = ["apple", "cat", "ball"]` and I want them to appear in that order left to right in each of three categories, so

```
sx = repeat(groupvals, inner=3)
...
p = groupedbar(..., group = sx, ...)
```
The resulting grouped bar plot has them alphabetically arranged, i.e. the bar for "ball" comes after that for "apple" in each category. Is there any way to override this behavior?

**Comment by MaximilianJHuber** [comment]
Please, implement this soon. The pull #309 changed the behavior of `groupedbar` and I cannot compensate without this tool.

**Comment by JonasIsensee** [comment]
Hi,

so I just figured out how to do it after a lot of digging.
(double post of  https://discourse.julialang.org/t/statplots-groupedbar-order-x-axis/13912/18?u=jonasisensee )

The issue is that in 
`RecipesPipeline.jl` there is 
    `group_labels = sort(collect(unique(v)))`
https://github.com/JuliaPlots/RecipesPipeline.jl/blob/304db22c33b64a902dd91606a8886ec371f62809/src/group.jl#L11

Now in theory there are `CategoricalArrays` for this purpose,
however `unique(ctg::CategoricalArray)` returns an ordinary `Vector{String}` instead of a new `CategoricalArray`.

Defining this solves the problem in this case
```
function Base.unique(ctg::CategoricalArray)
    l = levels(ctg)
    newctg = CategoricalArray(l)
    levels!(newctg, l)
end
```

```
ctg = CategoricalArray(["a", "b", "c", "a", "b", "c"])
levels!(ctg, ["c", "b", "a"])
groupedbar(1:6, group=ctg)
```
![test](https://user-images.githubusercontent.com/33990604/84487098-8d151200-ac9e-11ea-83f4-2bf62f893c5f.png)



Now for a permanent fix one would either have to change the definition of `Base.unique` in `CategoricalArrays` OR
find a different way of writing 
`sort(collect(unique(v)))`
that does the intended thing for both regular arrays and `CategoricalArrays`.

**Comment by mkborregaard** [comment]
Hey amazing @JonasIsensee

**Comment by mkborregaard** [comment]
Closed in https://github.com/JuliaPlots/RecipesPipeline.jl/pull/59
