### ISSUE TITLE
[BUG] Normalization not working for `groupedhist`

### ISSUE THREAD

**Issue by ValentinKaisermayer** [JuliaPlots/StatsPlots.jl#457]
If `group`s are used the bins are no longer normalized:
```julia
StatsPlots.groupedhist(
    [randn(1000) randn(1000) .+ 2.0], 
    group=repeat(["1", "2"], inner=1000), 
    bar_position=:doge, 
    normalize=true,
)
```
![bug](https://user-images.githubusercontent.com/50108075/125275683-9fcda080-e30f-11eb-9694-06512924cd4b.png)

**Comment by ValentinKaisermayer** [comment]
https://github.com/JuliaPlots/StatsPlots.jl/blob/b99a4ff6c760f0e1275bb54572c94da03a7bc81f/src/hist.jl#L100
shouldn't it be:
```julia
y[:,i] = normed ? h_i.weights / sum(h_i.weights) : h_i.weights
```
Which would yield:
![bug](https://user-images.githubusercontent.com/50108075/125278043-824e0600-e312-11eb-920f-6f5c479eadd9.png)

**Comment by sethaxen** [comment]
Thanks for the issue! First, this is definitely a bug, but the fix depends on what `normed` should mean here. The fix you have proposed would cause the area of each bin to correspond to `p(bin=i | group=j)` (`*inv(nbins)` when `bar_position=:dodge`), but suppose if group 1 has 100 points total, 50 of which are in bin A, while group 2 has only 1 point, which also falls in group A.
```julia
julia> x = [1; ones(50); fill(2, 50)];

julia> group=[1; fill(2, 100)];

julia> groupedhist(x; group=group, normed=false, title="normed=false")
```
![normed_false](https://user-images.githubusercontent.com/8673634/132705292-e79abf10-38aa-483a-9dec-44def28c866d.png)
```julia
julia> groupedhist(x; group=group, normed=true, title="normed=true")
```
![normed_true](https://user-images.githubusercontent.com/8673634/132705570-1cbe039e-1601-4f52-addc-15e09c0879f8.png)

This normalization causes group B to have the highest peak, which is misleading, given that it is not only the least abundant group in bin 1, it is also the least abundant group total. The problem is that the normalization hasn't taken into account the imbalance between the groups. i.e. we probably want the area of each bin to correspond to `p(bin=i | group=j) p(group=j)`, which has the added benefit that when one passes `bar_position=:stack`, then the heights of the stacks should correspond exactly to what one would get with `histogram` with `normed=true`.

**Comment by ValentinKaisermayer** [comment]
Matplotlib seems to do this a bit differently. They have a different normalization, if the bins are stacked or not. 
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html
In both cases the area under the curve evaluates to one.

**Comment by ValentinKaisermayer** [comment]
@sethaxen Is this what you had in mind?

```julia
StatsPlots.groupedhist(
    [1; ones(50); fill(2, 50)], 
    group=[1; fill(2, 100)], 
    bar_position=:doge, 
    normalize=true,
)
```
![hist](https://user-images.githubusercontent.com/50108075/134668501-014a3f94-f1da-445d-b3e7-acdf910f7b99.png)

```julia
StatsPlots.groupedhist(
    [1; ones(50); fill(2, 50)], 
    group=[1; fill(2, 100)], 
    bar_position=:doge, 
    normalize=false,
)
```
![hist](https://user-images.githubusercontent.com/50108075/134668596-11be913f-9ef6-4ce8-bbe1-ae9efb2cbb21.png)

**Comment by ValentinKaisermayer** [comment]
```julia
StatsPlots.groupedhist(
    [1; ones(50); fill(2, 50)], 
    group=[1; fill(2, 100)], 
    bar_position=:stack, 
    normalize=true,
)
```
![hist](https://user-images.githubusercontent.com/50108075/134669097-aded3544-7803-4685-b083-f9650ce89550.png)

```julia
StatsPlots.histogram(
    [1; ones(50); fill(2, 50)], 
    normalize=:probability,
)
```
![hist](https://user-images.githubusercontent.com/50108075/134670112-e8176eef-ed5d-4fbd-b3bd-6e55f171fc66.png)

**Comment by sethaxen** [comment]
@ValentinKaisermayer Yes, this looks perfect! I do think that for `bar_position=:dodge`, the bar heights should be multiplied by the number of groups to ensure that the areas are the same as for `bar_position=:stack`, but this would be a functional change and should be handled in a different PR.

**Comment by ValentinKaisermayer** [comment]
>  to ensure that the areas are the same

I think this would then be the same behavior as in [matplotlib](https://github.com/matplotlib/matplotlib/blob/4b0694561b8497ac1a102ae300923445394d8c3c/lib/matplotlib/axes/_axes.py#L6592).
