### ISSUE TITLE
Can't set groupedbar series colors

### ISSUE THREAD

**Issue by pearlzli** [JuliaPlots/StatsPlots.jl#67]
I'd like to set the color individually for each series in a grouped bar plot, e.g.

```julia
using Plots, StatPlots
Plots.gr()
data = rand(6, 3)

p1 = groupedbar(data, color = [:red, :green, :blue])
```

But this produces the following plot:

![p1](https://user-images.githubusercontent.com/6033297/28731302-5da38756-73a1-11e7-9799-428757c23eb7.png)

I've also tried substituting `color` for `fillcolor`, `seriescolor`, `linecolor`, and `markercolor`. It's only when I edit the series individually that I get the desired plot:

```julia
p2 = groupedbar(data)
p2.series_list[1].d[:fillcolor] = parse(Colorant, :red)
p2.series_list[2].d[:fillcolor] = parse(Colorant, :green)
p2.series_list[3].d[:fillcolor] = parse(Colorant, :blue)
```

![p2](https://user-images.githubusercontent.com/6033297/28731369-96005052-73a1-11e7-998d-996cc2b17926.png)

Is there a way to do this that I'm not aware of? I've looked through the StatPlots readme and the `groupedbar` code, and I haven't been able to figure it out. Thanks!

(Also, I'm not positive if this is a StatPlots issue, so if it isn't, I'll gladly open an issue in the appropriate package.)

**Comment by piever** [comment]
Have you tried `groupedbar(data, color = [:red :green :blue])` ?
To pass an attribute to the different series you need a (1, n) array.

**Comment by pearlzli** [comment]
Ah that's the trick - thank you!

**Comment by JontySinai** [comment]
Stumbled upon this issue today. @piever thanks for pointing out the reason. However thinking about the API here, the difference between passing (1,n) array vs (n,) array of colors is not just confusing but doesn't play well with what you'd expect, especially when working with a color scheme. For example setting

`groupedbar(data, color = palette(:auto)[1:3]`

won't work since `palette(:auto)[1:3]` has size `(3,)`, but

`groupedbar(data, color = reshape(palette(:auto)[1:3], (1,3)`

will work. My first instinct would be to just specify the color scheme directly, ie:

`groupedbar(data, color = :auto)`

rather than having to explicitly extract the 3 colors I want from a color scheme and then reshaping to the (1,n) format.
